# Data Cleaning

This notebook focuses on cleaning and preparing the retail sales dataset for analysis.

In [1]:
import pandas as pd
import numpy as np

## Load Raw Dataset

In [2]:
df = pd.read_csv("../data/raw/sales_data.csv")

In [3]:
df.head()

,order_id,order_date,customer_id,product_name,category,price,quantity_sold,product_cost,profit,stock_remaining,payment_method
0,ORD0001,2025-05-15,CUST226,Prosciutto Crudo 200g,Cured Meat,8.9,2,5.4,7.0,4,Cash
1,ORD0002,2025-02-03,CUST583,Parmigiano Reggiano 1kg,Cheese,27.9,2,18.5,18.8,88,Debit Card
2,ORD0003,2025-11-27,CUST865,Orecchiette 500g,Pasta,3.9,3,1.9,6.0,140,Debit Card
3,ORD0004,2025-08-17,CUST587,Parmigiano Reggiano 1kg,Cheese,27.9,2,18.5,18.8,34,Cash
4,ORD0005,2025-08-26,CUST175,Orange Marmalade 300g,Preserves,5.5,1,2.7,2.8,20,Cash

## Dataset Overview

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         1000 non-null   object
 1   order_date       1000 non-null   object
 2   customer_id      1000 non-null   object
 3   product_name     1000 non-null   object
 4   category         1000 non-null   object
 5   price            1000 non-null   float64
 6   quantity_sold    1000 non-null   int64
 7   product_cost     1000 non-null   float64
 8   profit           1000 non-null   float64
 9   stock_remaining  1000 non-null   int64
 10  payment_method   1000 non-null   object
dtypes: float64(3), int64(2), object(6)
memory usage: 86.1+ KB

In [5]:
df.describe()

             price  quantity_sold  product_cost       profit  stock_remaining
count  1000.000000     1000.00000    1000.00000  1000.000000       1000.00000
mean     13.132000        2.98900       8.26040    14.483900         73.63100
std      16.048927        1.40387      11.96091    16.396194         43.61182
min       2.900000        1.00000       1.20000     1.700000          0.00000
25%       5.500000        2.00000       2.70000     5.800000         36.00000
50%       6.900000        3.00000       4.10000    10.400000         72.00000
75%      14.900000        4.00000       9.20000    15.000000        110.00000
max      84.900000        5.00000      66.30000   103.000000        150.00000

## Simulate Real-World Data Issues

In [6]:
# Introduce missing values
df.loc[5, "payment_method"] = np.nan
df.loc[12, "stock_remaining"] = np.nan

# Introduce inconsistent category naming
df.loc[20, "category"] = "Cheeses"
df.loc[45, "category"] = "cured meat"

# Duplicate one row
duplicate_row = df.iloc[30]

df = pd.concat([df, duplicate_row.to_frame().T], ignore_index=True)

## Check Missing Values

In [7]:
df.isnull().sum()

order_id           0
order_date         0
customer_id        0
product_name       0
category           0
price              0
quantity_sold      0
product_cost       0
profit             0
stock_remaining    1
payment_method     1
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(1)

In [9]:
df["category"].unique()

array(['Cured Meat', 'Cheese', 'Pasta', 'Preserves', 'Wine', 'Bakery',
       'Cheeses', 'Olive Oil', 'cured meat'], dtype=object)

## Handle Missing Values

In [10]:
df["payment_method"] = df["payment_method"].fillna("Unknown")

df["stock_remaining"] = df["stock_remaining"].fillna(
    df["stock_remaining"].median()
)

C:\Users\Francesco\AppData\Local\Temp\ipykernel_10420\3825752729.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["stock_remaining"] = df["stock_remaining"].fillna(

## Standardize Category Names

In [11]:
df["category"] = df["category"].replace({
    "Cheeses": "Cheese",
    "cured meat": "Cured Meat"
})

## Remove Duplicate Rows

In [12]:
df = df.drop_duplicates()

## Verify Cleaned Dataset

In [13]:
df.isnull().sum()

order_id           0
order_date         0
customer_id        0
product_name       0
category           0
price              0
quantity_sold      0
product_cost       0
profit             0
stock_remaining    0
payment_method     0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df["category"].unique()

array(['Cured Meat', 'Cheese', 'Pasta', 'Preserves', 'Wine', 'Bakery',
       'Olive Oil'], dtype=object)

## Export Cleaned Dataset

In [16]:
df.to_csv("../data/cleaned/cleaned_sales_data.csv", index=False)